# dns 自动安装，可选"coredns"和“kubedns”
dns_install: "yes"

# metric server 自动安装
metricsserver_install: "yes"

# dashboard 自动安装
dashboard_install: "yes"

# ingress 自动安装，可选 "traefik" 和 "nginx-ingress"
ingress_install: "no"
ingress_backend: "traefik"
traefik_offline: "traefik_v1.7.4.tar"
nginx_ingress_offline: "nginx_ingress_0.21.0.tar"

# heapster 自动安装
heapster_install: "yes"

# metallb 自动安装
metallb_install: "no"
# 模式选择: 二层 "layer2" 或者三层 "bgp"
metallb_protocol: "layer2"
metallb_offline: "metallb_v0.7.3.tar"
metallb_vip_pool: "192.168.1.240/29"

# efk 自动安装
#efk_install: "no"

# prometheus 自动安装
#prometheus_install: "no"

