- block:
    - name: 在deploy 节点创建相关目录
      file: path={{ item }} state=directory
      with_items:
      - /opt/kube/kube-system/coredns
    
    # DNS文件中部分参数根据hosts文件设置而定，因此需要用template模块替换参数
    - name: 准备 DNS的部署文件
      template: src={{ item }}.yaml.j2 dest=/opt/kube/kube-system/{{ item }}/{{ item }}.yaml
      with_items:
      - coredns
    
    - name: 获取所有已经创建的POD信息
      command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
      register: pod_info
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true

- block:
    - name: 创建{{ dns_backend }}部署
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/{{ dns_backend }}"
      run_once: true
      delegate_to: "{{ groups.deploy[0] }}"
  when: 
  - '"coredns" not in pod_info.stdout'
  - 'dns_install == "yes"'
  ignore_errors: true

- block:
    - name: 创建 metrics-server部署
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/metrics-server"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true
  when: '"metrics-server" not in pod_info.stdout and metricsserver_install == "yes"'
  ignore_errors: true

- block:
    - name: 创建 dashboard部署
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/dashboard"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true
  when: '"kubernetes-dashboard" not in pod_info.stdout and dashboard_install == "yes"'
  ignore_errors: true

- import_tasks: ingress.yml
  when: '"ingress-controller" not in pod_info.stdout and ingress_install == "yes"'

- block:
    - name: 准备heapster influxdb grafana的部署文件
      template: src={{ item }}.yaml.j2 dest={{ base_dir }}/manifests/heapster/{{ item }}.yaml
      with_items:
      - heapster
      - grafana
      - influxdb
    - name: 创建 heapster部署
      shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/heapster/heapster.yaml"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true
  when: '"heapster" not in pod_info.stdout and heapster_install == "yes"'
  ignore_errors: true

- block:
    - name: 生成 metallb 相关 manifests
      template: src=metallb/{{ item }}.j2 dest=/opt/kube/kube-system/{{ item }}
      with_items:
      - "metallb.yaml"
      - "{{ metallb_protocol }}.yaml"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true

    - name: 创建 metallb controller 部署
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/metallb.yaml"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true

    - name: 创建 metallb configmap
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/{{ metallb_protocol }}.yaml"
      delegate_to: "{{ groups.deploy[0] }}"
      run_once: true
  when: '"metallb" not in pod_info.stdout and metallb_install == "yes"'
  ignore_errors: true

