apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
  labels:
    app: apigateway-svc
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 8080
      name: business
      targetPort: 8080
      nodePort: 30005
    - port: 5005
      name: debug
      targetPort: 5005
      nodePort: 20005
  selector:
    app: apigateway-app
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-remote-svc
  labels:
    app: apigateway-remote-svc
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 18082
      name: remote
      targetPort: 18082
  selector:
    app: apigateway-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apigateway-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway-app
    spec:
      containers:
      - name: apigateway-app
        image: 172.16.12.236/platform/apigateway:20190418100702dailyupdate
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1024Mi